spring.application.name=ECom
spring.datasource.url=jdbc:postgresql://localhost:5432/ecom
spring.datasource.username=postgres
spring.datasource.password=
spring.security.user.name=admin
spring.security.user.password=admin